name: dies_und_das
version: 0.1.0
summary: Svens Swiss Spezialtaschenmesser
description: Diverse Tools für den täglichen Gebrauch

confinement: strict
base: core18
grade: stable

slots:
  dbus-super-cool-app: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.buschke.dies_und_das # adjust accordingly to your app name and

apps:
  super-cool-app:
    command: dies_und_das
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-dies-und-das
parts:
  super-cool-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
